### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by saroqe** [hadysalama/PyShell#1]
I made a similar shell, but for all Operating Systems, and for beginners that are building operating systems.
That looks hella complicated to me, sorry if you think i stole anything, i did search PyShell up to see if there is any other but there was only stuff like "Remote Access Trojan" and stuff like that, so i thought i could make one

**Comment by hadysalama** [comment]
All good! I learned this style of coding in my Operating Systems class. Its the main convention of how to build shells. Mine works mainly on Linux/Unix. You didn't implement a full shell. You implemented a list of commands which is a great place to start learning. If you could name yours something other than PyShell I think that would be more accurate. I would call yours CommandHelp or PyCMD. Btw os.system can take user input as a string so the user could use any command they want.

**Comment by hadysalama** [comment]
> I made a similar shell, but for all Operating Systems, and for beginners that are building operating systems.
> 
> That looks hella complicated to me, sorry if you think i stole anything, i did search PyShell up to see if there is any other but there was only stuff like "Remote Access Trojan" and stuff like that, so i thought i could make one

All good! I learned this style of coding in my Operating Systems class. Its the main convention of how to build shells. Mine works on all platforms and is architecture independent so it can run on your phone. You didn't implement a full shell. You implemented a list of commands which is a great place to start learning. If you could name yours something other than PyShell I think that would be more accurate. I would call yours CommandHelp or PyCMD. Btw os.system can take user input as a string so the user could use any command they want.

**Comment by saroqe** [comment]
> > I made a similar shell, but for all Operating Systems, and for beginners that are building operating systems.
> > That looks hella complicated to me, sorry if you think i stole anything, i did search PyShell up to see if there is any other but there was only stuff like "Remote Access Trojan" and stuff like that, so i thought i could make one
> 
> All good! I learned this style of coding in my Operating Systems class. Its the main convention of how to build shells. Mine works on all platforms and is architecture independent so it can run on your phone. You didn't implement a full shell. You implemented a list of commands which is a great place to start learning. If you could name yours something other than PyShell I think that would be more accurate. I would call yours CommandHelp or PyCMD. Btw os.system can take user input as a string so the user could use any command they want.

Oh man, i forgot this even existed. I was only experimenting back then, and did not intend to make a proper working one. I was only just seeing what i could do.
